# Module - 1

In [1]:
import pandas as p
import numpy as n

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [35]:
data=p.read_csv('human.csv')

In [36]:
data.head()

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [37]:
data['sl'].value_counts()

3    126
1    126
0    126
2    126
4    126
Name: sl, dtype: int64

In [5]:
data.shape

(630, 9)

In [6]:
data.size

5670

In [7]:
data.isnull()

sr     rr      t     lm     bo    rem   sr.1     hr     sl
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
625  False  False  False  False  False  False  False  False  False
626  False  False  False  False  False  False  False  False  False
627  False  False  False  False  False  False  False  False  False
628  False  False  False  False  False  False  False  False  False
629  False  False  False  False  False  False  False  False  False

[630 rows x 9 columns]

In [8]:
data.columns

Index(['sr', 'rr', 't', 'lm', 'bo', 'rem', 'sr.1', 'hr', 'sl'], dtype='object')

In [9]:
data['sl'].unique()

array([3, 1, 0, 2, 4], dtype=int64)

In [10]:
data[data["sl"] == 2]

sr      rr       t      lm      bo    rem   sr.1     hr  sl
10   73.44  21.344  93.344  11.344  91.344  91.72  4.016  63.36   2
19   63.68  20.368  92.368  10.368  90.368  86.84  2.552  60.92   2
20   77.60  21.760  93.760  11.760  91.760  93.80  4.640  64.40   2
21   77.28  21.728  93.728  11.728  91.728  93.64  4.592  64.32   2
22   69.76  20.976  92.976  10.976  90.976  89.88  3.464  62.44   2
..     ...     ...     ...     ...     ...    ...    ...    ...  ..
614  62.40  20.240  92.240  10.240  90.240  86.20  2.360  60.60   2
617  71.68  21.168  93.168  11.168  91.168  90.84  3.752  62.92   2
622  65.44  20.544  92.544  10.544  90.544  87.72  2.816  61.36   2
625  69.60  20.960  92.960  10.960  90.960  89.80  3.440  62.40   2
629  73.92  21.392  93.392  11.392  91.392  91.96  4.088  63.48   2

[126 rows x 9 columns]

In [11]:
data[data["sl"] == 3]

sr      rr       t     lm      bo    rem   sr.1     hr  sl
0    93.80  25.680  91.840  16.60  89.840  99.60  1.840  74.20   3
1    91.64  25.104  91.552  15.88  89.552  98.88  1.552  72.76   3
3    85.76  23.536  90.768  13.92  88.768  96.92  0.768  68.84   3
14   87.80  24.080  91.040  14.60  89.040  97.60  1.040  70.20   3
17   86.24  23.664  90.832  14.08  88.832  97.08  0.832  69.16   3
..     ...     ...     ...    ...     ...    ...    ...    ...  ..
600  93.56  25.616  91.808  16.52  89.808  99.52  1.808  74.04   3
605  94.04  25.744  91.872  16.68  89.872  99.68  1.872  74.36   3
610  93.68  25.648  91.824  16.56  89.824  99.56  1.824  74.12   3
612  88.88  24.368  91.184  14.96  89.184  97.96  1.184  70.92   3
615  82.88  22.768  90.384  12.96  88.384  95.96  0.384  66.92   3

[126 rows x 9 columns]

In [12]:
a = data["bo"].unique()
a.sort()
print(a)

[82.    82.048 82.096 82.144 82.192 82.24  82.288 82.336 82.384 82.432
 82.48  82.528 82.576 82.624 82.672 82.72  82.768 82.816 82.864 82.912
 82.96  83.008 83.056 83.104 83.152 83.2   83.248 83.296 83.344 83.392
 83.44  83.488 83.536 83.584 83.632 83.68  83.728 83.776 83.824 83.872
 83.92  83.968 84.016 84.064 84.112 84.16  84.208 84.256 84.304 84.352
 84.4   84.448 84.496 84.544 84.592 84.64  84.688 84.736 84.784 84.832
 84.88  84.928 84.976 85.024 85.072 85.12  85.168 85.216 85.264 85.312
 85.36  85.408 85.456 85.504 85.552 85.6   85.648 85.696 85.744 85.792
 85.84  85.888 85.936 85.984 86.032 86.08  86.128 86.176 86.224 86.272
 86.32  86.368 86.416 86.464 86.512 86.56  86.608 86.656 86.704 86.752
 86.8   86.848 86.896 86.944 86.992 87.04  87.088 87.136 87.184 87.232
 87.28  87.328 87.376 87.424 87.472 87.52  87.568 87.616 87.664 87.712
 87.76  87.808 87.856 87.904 87.952 88.    88.016 88.032 88.048 88.064
 88.08  88.096 88.112 88.128 88.144 88.16  88.176 88.192 88.208 88.224
 88.24

In [13]:
data["hr"].unique()

array([74.2 , 72.76, 60.  , 68.84, 53.12, 58.44, 52.  , 55.  , 50.28,
       57.76, 63.36, 59.64, 53.6 , 75.72, 70.2 , 56.16, 56.32, 69.16,
       66.04, 60.92, 64.4 , 64.32, 62.44, 70.36, 71.64, 56.84, 64.64,
       55.48, 74.84, 60.52, 54.12, 75.64, 52.68, 84.76, 69.48, 53.48,
       81.32, 51.12, 81.8 , 60.24, 61.4 , 63.84, 54.28, 63.32, 82.28,
       60.72, 79.16, 58.36, 76.44, 54.6 , 56.8 , 73.8 , 51.84, 58.04,
       63.92, 78.84, 73.56, 70.04, 59.24, 80.84, 65.72, 51.6 , 60.4 ,
       76.12, 55.12, 54.92, 60.12, 82.84, 53.28, 55.24, 75.48, 58.84,
       50.16, 53.68, 80.04, 77.  , 58.24, 71.72, 75.  , 55.32, 55.28,
       56.96, 76.68, 62.08, 57.44, 56.2 , 55.8 , 73.32, 80.6 , 61.28,
       69.4 , 62.  , 84.52, 50.2 , 60.8 , 80.68, 63.8 , 64.24, 65.  ,
       84.04, 78.04, 50.04, 78.44, 56.76, 60.36, 60.56, 64.8 , 77.4 ,
       57.2 , 62.24, 76.52, 52.44, 72.04, 61.72, 79.8 , 62.16, 64.  ,
       54.52, 57.48, 57.64, 71.88, 78.28, 59.04, 67.4 , 80.28, 80.52,
       61.44, 58.6 ,

In [14]:
data["sr"].unique()

array([ 93.8  ,  91.64 ,  60.   ,  85.76 ,  48.12 ,  56.88 ,  47.   ,
        50.   ,  45.28 ,  55.52 ,  73.44 ,  59.28 ,  48.6  ,  96.288,
        87.8  ,  52.32 ,  52.64 ,  86.24 ,  81.56 ,  63.68 ,  77.6  ,
        77.28 ,  69.76 ,  88.04 ,  89.96 ,  53.68 ,  78.56 ,  50.96 ,
        94.76 ,  62.08 ,  49.12 ,  96.256,  47.68 ,  99.904,  86.72 ,
        48.48 ,  98.528,  46.12 ,  98.72 ,  60.96 ,  65.6  ,  75.36 ,
        49.28 ,  73.28 ,  98.912,  62.88 ,  97.664,  56.72 ,  96.576,
        49.6  ,  53.6  ,  93.2  ,  46.84 ,  56.08 ,  75.68 ,  97.536,
        92.84 ,  87.56 ,  58.48 ,  98.336,  81.08 ,  46.6  ,  61.6  ,
        96.448,  50.24 ,  49.92 ,  60.48 ,  99.136,  48.28 ,  50.48 ,
        96.192,  57.68 ,  45.16 ,  48.68 ,  98.016,  96.8  ,  56.48 ,
        90.08 ,  96.   ,  50.64 ,  50.56 ,  53.92 ,  96.672,  68.32 ,
        54.88 ,  52.4  ,  51.6  ,  92.48 ,  98.24 ,  65.12 ,  86.6  ,
        68.   ,  99.808,  45.2  ,  63.2  ,  98.272,  75.2  ,  76.96 ,
        80.   ,  99.

In [15]:
df = data.dropna()

In [16]:
df

sr      rr       t      lm      bo     rem   sr.1     hr  sl
0    93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1    91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2    60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3    85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4    48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..      ...     ...     ...     ...     ...     ...    ...    ...  ..
625  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 9 columns]

In [17]:
df.isnull().sum()

sr      0
rr      0
t       0
lm      0
bo      0
rem     0
sr.1    0
hr      0
sl      0
dtype: int64

In [18]:
df.shape

(630, 9)

In [19]:
print("Maximum Age :",df["rem"].max())
print("Minimum Age :",df["rem"].min())
print("Mean of Age :","%.2f" %   df["rem"].mean())
print("Median of Age :","%.2f" %   df["rem"].median())

Maximum Age : 105.0
Minimum Age : 60.0
Mean of Age : 88.50
Median of Age : 90.00


In [20]:
df.describe()

sr          rr          t          lm          bo         rem  \
count  630.000000  630.000000  630.00000  630.000000  630.000000  630.000000   
mean    71.600000   21.800000   92.80000   11.700000   90.900000   88.500000   
std     19.372833    3.966111    3.52969    4.299629    3.902483   11.893747   
min     45.000000   16.000000   85.00000    4.000000   82.000000   60.000000   
25%     52.500000   18.500000   90.50000    8.500000   88.500000   81.250000   
50%     70.000000   21.000000   93.00000   11.000000   91.000000   90.000000   
75%     91.250000   25.000000   95.50000   15.750000   94.250000   98.750000   
max    100.000000   30.000000   99.00000   19.000000   97.000000  105.000000   

             sr.1          hr          sl  
count  630.000000  630.000000  630.000000  
mean     3.700000   64.500000    2.000000  
std      3.054572    9.915277    1.415337  
min      0.000000   50.000000    0.000000  
25%      0.500000   56.250000    1.000000  
50%      3.500000   62.500000    2.000000  
75%      6.500000   72.500000    3.000000  
max      9.000000   85.000000    4.000000

In [21]:
df.corr()

sr        rr         t        lm        bo       rem      sr.1  \
sr    1.000000  0.976268 -0.902475  0.981078 -0.903140  0.950600 -0.920554   
rr    0.976268  1.000000 -0.889237  0.991738 -0.889210  0.935572 -0.891855   
t    -0.902475 -0.889237  1.000000 -0.896412  0.998108 -0.857299  0.954860   
lm    0.981078  0.991738 -0.896412  1.000000 -0.898527  0.964703 -0.901102   
bo   -0.903140 -0.889210  0.998108 -0.898527  1.000000 -0.862136  0.950189   
rem   0.950600  0.935572 -0.857299  0.964703 -0.862136  1.000000 -0.893952   
sr.1 -0.920554 -0.891855  0.954860 -0.901102  0.950189 -0.893952  1.000000   
hr    0.976268  1.000000 -0.889237  0.991738 -0.889210  0.935572 -0.891855   
sl    0.975322  0.963516 -0.962354  0.971071 -0.961092  0.951988 -0.973036   

            hr        sl  
sr    0.976268  0.975322  
rr    1.000000  0.963516  
t    -0.889237 -0.962354  
lm    0.991738  0.971071  
bo   -0.889210 -0.961092  
rem   0.935572  0.951988  
sr.1 -0.891855 -0.973036  
hr    1.000000  0.963516  
sl    0.963516  1.000000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sr      630 non-null    float64
 1   rr      630 non-null    float64
 2   t       630 non-null    float64
 3   lm      630 non-null    float64
 4   bo      630 non-null    float64
 5   rem     630 non-null    float64
 6   sr.1    630 non-null    float64
 7   hr      630 non-null    float64
 8   sl      630 non-null    int64  
dtypes: float64(8), int64(1)
memory usage: 44.4 KB


In [23]:
p.crosstab(df["rem"], df["sl"])

sl      0  1  2  3  4
rem                  
60.00   1  0  0  0  0
60.16   1  0  0  0  0
60.32   1  0  0  0  0
60.48   1  0  0  0  0
60.64   1  0  0  0  0
...    .. .. .. .. ..
104.84  0  0  0  0  1
104.88  0  0  0  0  1
104.92  0  0  0  0  1
104.96  0  0  0  0  1
105.00  0  0  0  0  1

[626 rows x 5 columns]

In [24]:
df.groupby(["sr.1","sl"]).groups

{(0.0, 3): [99], (0.0, 4): [13, 31, 33, 37, 39, 45, 47, 49, 56, 60, 64, 68, 71, 75, 76, 79, 83, 89, 93, 96, 100, 101, 103, 108, 111, 115, 122, 125, 126, 129, 132, 138, 152, 153, 158, 159, 160, 164, 168, 169, 177, 192, 194, 204, 207, 221, 225, 228, 231, 237, 240, 243, 251, 258, 260, 270, 271, 274, 278, 290, 292, 294, 306, 321, 323, 325, 330, 334, 345, 349, 351, 352, 354, 357, 364, 370, 377, 380, 390, 392, 394, 402, 411, 412, 417, 421, 422, 428, 430, 437, 440, 445, 446, 458, 460, 462, 479, 485, 489, 491, ...], (0.016, 3): [224], (0.032, 3): [544], (0.048, 3): [400], (0.064, 3): [502], (0.08, 3): [528], (0.096, 3): [350], (0.112, 3): [566], (0.128, 3): [244], (0.144, 3): [61], (0.16, 3): [248], (0.176, 3): [359], (0.192, 3): [141], (0.208, 3): [18], (0.224, 3): [532], (0.24, 3): [418], (0.256, 3): [261], (0.272, 3): [515], (0.288, 3): [487], (0.304, 3): [211], (0.32, 3): [447], (0.336, 3): [318], (0.352, 3): [549], (0.368, 3): [253], (0.384, 3): [615], (0.4, 3): [584], (0.416, 3): [238], 

In [25]:
df["sl"].value_counts()

3    126
1    126
0    126
2    126
4    126
Name: sl, dtype: int64

In [26]:
df["hr"].value_counts()

65.00    2
60.00    2
75.00    2
55.00    2
53.52    1
        ..
73.72    1
69.96    1
52.40    1
64.44    1
63.48    1
Name: hr, Length: 626, dtype: int64

In [27]:
p.Categorical(df["rr"]).describe()

counts     freqs
categories                  
16.0             1  0.001587
16.016           1  0.001587
16.032           1  0.001587
16.048           1  0.001587
16.064           1  0.001587
...            ...       ...
29.872           1  0.001587
29.904           1  0.001587
29.936           1  0.001587
29.968           1  0.001587
30.0             1  0.001587

[626 rows x 2 columns]

In [28]:
p.Categorical(df["sr.1"]).describe()

counts     freqs
categories                  
0.0            127  0.201587
0.016            1  0.001587
0.032            1  0.001587
0.048            1  0.001587
0.064            1  0.001587
...            ...       ...
8.936            1  0.001587
8.952            1  0.001587
8.968            1  0.001587
8.984            1  0.001587
9.0              1  0.001587

[501 rows x 2 columns]

In [29]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
625    False
626    False
627    False
628    False
629    False
Length: 630, dtype: bool

In [30]:
sum(df.duplicated())

0

In [33]:
df['sl'].value_counts()

3    126
1    126
0    126
2    126
4    126
Name: sl, dtype: int64